import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { spawn } from 'node:child_process';

export function loadEnv(file){if(!fs.existsSync(file))return;for(const line of fs.readFileSync(file,'utf8').split(/\r?\n/)){const m=line.match(/^\s*([A-Z0-9_]+)=(.*)\s*$/);if(m&&!process.env[m[1]])process.env[m[1]]=m[2].replace(/^['"]|['"]$/g,'')}}
export const uid=()=>crypto.randomBytes(9).toString('base64url');
export const nowIso=()=>new Date().toISOString();
export function json(res,status,data){const b=Buffer.from(JSON.stringify(data));res.writeHead(status,{'content-type':'application/json; charset=utf-8','content-length':b.length});res.end(b)}
export async function bodyJson(req,limit=15_000_000){let s='';for await(const c of req){s+=c;if(s.length>limit)throw new Error('Requête trop volumineuse')}if(!s)return{};return JSON.parse(s)}
function key(secret){return crypto.createHash('sha256').update(secret).digest()}
export function encrypt(v,secret){if(!v)return'';const iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',key(secret),iv),enc=Buffer.concat([c.update(v,'utf8'),c.final()]),tag=c.getAuthTag();return [iv,tag,enc].map(x=>x.toString('base64url')).join('.')}
export function decrypt(v,secret){if(!v)return'';try{const [a,b,c]=v.split('.').map(x=>Buffer.from(x,'base64url')),d=crypto.createDecipheriv('aes-256-gcm',key(secret),a);d.setAuthTag(b);return Buffer.concat([d.update(c),d.final()]).toString('utf8')}catch{return''}}

const demoHooks=['Personne ne te montre ce détail…','J’aurais aimé connaître ça avant.','Ce petit objet règle un problème pénible.','Le test le plus simple pour savoir si ça vaut le coup.','Je pensais que c’était gadget… jusqu’à ce test.'];
function demoConcept(product,niche,format,i=0){const name=product?.name||`astuce ${niche}`,hook=demoHooks[i%demoHooks.length];return{title:`${name} — angle ${i+1}`,hook,hook_score:Math.max(55,90-i*5),script:`Voici ${name}. On montre le problème de départ, le produit en situation et le résultat réel, sans exagération. ${product?.notes||'Utilise uniquement des caractéristiques réellement vérifiées.'} L’objectif est une démonstration courte, utile et crédible, avec une conclusion claire.`,caption:`${name} : démonstration simple. #${String(niche).replace(/\s+/g,'')} #astuce #produit`,cta:'Tu peux vérifier le produit et ses détails depuis la fiche associée.',visual_beats:['Problème en 2 secondes','Produit en gros plan','Démonstration','Résultat réel','CTA discret']}}
async function openaiJson(prompt){const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'content-type':'application/json'},body:JSON.stringify({model:process.env.OPENAI_TEXT_MODEL||'gpt-5.6-luna',input:prompt,text:{format:{type:'json_object'}}})});const d=await r.json();if(!r.ok)throw new Error(d?.error?.message||`OpenAI ${r.status}`);const text=d.output_text||d.output?.flatMap(x=>x.content||[]).find(x=>x.type==='output_text')?.text;if(!text)throw new Error('OpenAI n’a retourné aucun JSON');return JSON.parse(text)}
export async function testOpenAI(){if(!process.env.OPENAI_API_KEY)throw new Error('Clé OpenAI absente');const r=await fetch('https://api.openai.com/v1/models',{headers:{authorization:`Bearer ${process.env.OPENAI_API_KEY}`}});if(!r.ok)throw new Error(`Clé OpenAI refusée (${r.status})`);return true}
export async function generateConceptVariants({product,niche,format,count=3}){count=Math.max(1,Math.min(5,count));if(process.env.DEMO_MODE==='true'||!process.env.OPENAI_API_KEY)return Array.from({length:count},(_,i)=>demoConcept(product,niche,format,i));const facts=product?JSON.stringify({name:product.name,category:product.category,price:product.price,commission_rate:product.commission_rate,notes:product.notes}):'aucun produit';const prompt=`Tu crées des scripts TikTok faceless orientés conversion, mais exacts et non trompeurs. Produit/faits autorisés: ${facts}. Niche: ${niche}. Format: ${format}. Génère exactement ${count} variantes vraiment différentes. Chaque variante: title, hook très court, hook_score/100, script 75-120 mots, caption avec 2 à 5 hashtags pertinents, cta discret, visual_beats (5 éléments). N’invente aucune caractéristique produit absente. Pas de faux avis, fausse rareté, promesse médicale ou financière. JSON strict: {"variants":[...]}.`;const d=await openaiJson(prompt);return (d.variants||[]).slice(0,count)}
export async function synthesizeSpeech(text,outFile){fs.mkdirSync(path.dirname(outFile),{recursive:true});if(process.env.DEMO_MODE==='true'||!process.env.OPENAI_API_KEY){await run('ffmpeg',['-y','-f','lavfi','-i','anullsrc=r=44100:cl=mono','-t','14','-c:a','aac',outFile]);return outFile}const r=await fetch('https://api.openai.com/v1/audio/speech',{method:'POST',headers:{authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'content-type':'application/json'},body:JSON.stringify({model:process.env.OPENAI_TTS_MODEL||'gpt-4o-mini-tts',voice:process.env.OPENAI_TTS_VOICE||'coral',input:text,format:'mp3'})});if(!r.ok)throw new Error(`TTS ${r.status}: ${(await r.text()).slice(0,400)}`);fs.writeFileSync(outFile,Buffer.from(await r.arrayBuffer()));return outFile}
export async function generateVisual({product,concept,outFile}){fs.mkdirSync(path.dirname(outFile),{recursive:true});if(process.env.DEMO_MODE==='true'||!process.env.OPENAI_API_KEY)return null;const facts=[product?.name,product?.category,product?.notes].filter(Boolean).join(' — ');const prompt=`Create a clean vertical commercial-style background image for a short social video. Subject: ${facts||concept.title}. Show only details supported by the description. No text, no logos, no watermark, no people making endorsements. Modern realistic product-demo composition, neutral background, room for captions, vertical 1024x1536.`;const r=await fetch('https://api.openai.com/v1/images/generations',{method:'POST',headers:{authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'content-type':'application/json'},body:JSON.stringify({model:process.env.OPENAI_IMAGE_MODEL||'gpt-image-2.5-flare',prompt,size:'1024x1536',quality:'medium',output_format:'jpeg'})});const d=await r.json();if(!r.ok)throw new Error(d?.error?.message||`Image OpenAI ${r.status}`);const b64=d?.data?.[0]?.b64_json;if(!b64)return null;fs.writeFileSync(outFile,Buffer.from(b64,'base64'));return outFile}
function escDrawtext(s=''){return String(s).replace(/\\/g,'\\\\').replace(/:/g,'\\:').replace(/'/g,"\\'").replace(/%/g,'\\%').replace(/\n/g,' ')}
function subtitleFilters(text,duration=18){const parts=String(text||'').split(/(?<=[.!?])\s+/).filter(Boolean).slice(0,6);if(!parts.length)return[];const slot=duration/parts.length;return parts.map((p,i)=>`drawtext=fontfile=/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf:text='${escDrawtext(p.slice(0,115))}':fontcolor=white:fontsize=38:x=(w-text_w)/2:y=1380:box=1:boxcolor=black@0.62:boxborderw=18:enable='between(t,${(i*slot).toFixed(2)},${((i+1)*slot).toFixed(2)})'`)}
export async function audioDuration(file){return new Promise((resolve)=>{const p=spawn('ffprobe',['-v','error','-show_entries','format=duration','-of','default=noprint_wrappers=1:nokey=1',file]);let s='';p.stdout.on('data',d=>s+=d);p.on('close',()=>resolve(Math.max(6,Math.min(60,Number(s)||18))));p.on('error',()=>resolve(18))})}
export async function renderVerticalVideo({concept,audioFile,outFile,product,imageFile}){fs.mkdirSync(path.dirname(outFile),{recursive:true});const duration=await audioDuration(audioFile),hook=escDrawtext(concept.hook.slice(0,100)),name=escDrawtext((product?.name||concept.title).slice(0,72));const overlays=[`drawtext=fontfile=/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf:text='${hook}':fontcolor=white:fontsize=60:x=(w-text_w)/2:y=170:box=1:boxcolor=black@0.62:boxborderw=24`,`drawtext=fontfile=/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf:text='${name}':fontcolor=white:fontsize=42:x=(w-text_w)/2:y=1040:box=1:boxcolor=black@0.42:boxborderw=18`,...subtitleFilters(concept.script,duration)].join(',');let args;if(imageFile&&fs.existsSync(imageFile)){args=['-y','-loop','1','-i',imageFile,'-i',audioFile,'-vf',`scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920,zoompan=z='min(zoom+0.0005,1.08)':d=1:s=1080x1920:fps=30,${overlays}`,'-map','0:v','-map','1:a','-c:v','libx264','-preset','veryfast','-pix_fmt','yuv420p','-c:a','aac','-b:a','128k','-t',String(duration),'-movflags','+faststart',outFile]}else{args=['-y','-f','lavfi','-i','color=c=0x16171c:s=1080x1920:r=30','-i',audioFile,'-vf',overlays,'-map','0:v','-map','1:a','-c:v','libx264','-preset','veryfast','-pix_fmt','yuv420p','-c:a','aac','-b:a','128k','-shortest','-movflags','+faststart',outFile]}await run('ffmpeg',args);return outFile}
export function run(cmd,args){return new Promise((resolve,reject)=>{const p=spawn(cmd,args,{stdio:['ignore','pipe','pipe']});let err='';p.stderr.on('data',d=>err+=d.toString());p.on('error',reject);p.on('close',code=>code===0?resolve():reject(new Error(`${cmd} exited ${code}: ${err.slice(-1800)}`)))})}
export async function commandExists(cmd){return new Promise(resolve=>{const p=spawn(cmd,['-version']);p.on('error',()=>resolve(false));p.on('close',c=>resolve(c===0))})}

export async function tiktokExchangeCode(code){const form=new URLSearchParams({client_key:process.env.TIKTOK_CLIENT_KEY||'',client_secret:process.env.TIKTOK_CLIENT_SECRET||'',code,grant_type:'authorization_code',redirect_uri:process.env.TIKTOK_REDIRECT_URI||''}),r=await fetch('https://open.tiktokapis.com/v2/oauth/token/',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:form}),d=await r.json();if(!r.ok||d.error)throw new Error(d.error_description||d.error||`TikTok OAuth ${r.status}`);return d}
export async function tiktokRefresh(refreshToken){const form=new URLSearchParams({client_key:process.env.TIKTOK_CLIENT_KEY||'',client_secret:process.env.TIKTOK_CLIENT_SECRET||'',grant_type:'refresh_token',refresh_token:refreshToken}),r=await fetch('https://open.tiktokapis.com/v2/oauth/token/',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:form}),d=await r.json();if(!r.ok||d.error)throw new Error(d.error_description||d.error||`TikTok refresh ${r.status}`);return d}
export async function tiktokCreatorInfo(token){const r=await fetch('https://open.tiktokapis.com/v2/post/publish/creator_info/query/',{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json; charset=UTF-8'},body:'{}'}),d=await r.json();if(!r.ok||d?.error?.code!=='ok')throw new Error(d?.error?.message||`Creator info ${r.status}`);return d.data}
export async function tiktokInitVideo(token,{fileSize,title,privacyLevel='SELF_ONLY',disableComment=false,disableDuet=false,disableStitch=false}){const body={post_info:{title,privacy_level:privacyLevel,disable_comment:disableComment,disable_duet:disableDuet,disable_stitch:disableStitch,is_aigc:true},source_info:{source:'FILE_UPLOAD',video_size:fileSize,chunk_size:fileSize,total_chunk_count:1}},r=await fetch('https://open.tiktokapis.com/v2/post/publish/video/init/',{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json; charset=UTF-8'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok||d?.error?.code!=='ok')throw new Error(d?.error?.message||`TikTok init ${r.status}`);return d.data}
export async function tiktokUploadVideo(uploadUrl,filePath){const buf=fs.readFileSync(filePath),size=buf.length,r=await fetch(uploadUrl,{method:'PUT',headers:{'content-type':'video/mp4','content-length':String(size),'content-range':`bytes 0-${size-1}/${size}`},body:buf});if(!r.ok)throw new Error(`TikTok upload ${r.status}: ${(await r.text()).slice(0,300)}`)}
export async function tiktokPostStatus(token,publishId){const r=await fetch('https://open.tiktokapis.com/v2/post/publish/status/fetch/',{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json; charset=UTF-8'},body:JSON.stringify({publish_id:publishId})}),d=await r.json();if(!r.ok||d?.error?.code!=='ok')throw new Error(d?.error?.message||`TikTok status ${r.status}`);return d.data}
export async function tiktokQueryVideos(token,ids){const fields='id,view_count,like_count,comment_count,share_count,title,create_time,is_aigc',r=await fetch(`https://open.tiktokapis.com/v2/video/query/?fields=${encodeURIComponent(fields)}`,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify({filters:{video_ids:ids.slice(0,20)}})}),d=await r.json();if(!r.ok||!(d?.error?.code==='ok'||d?.error?.code===0))throw new Error(d?.error?.message||`TikTok video query ${r.status}`);return d.data||{videos:[]}}
