import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { DatabaseSync } from 'node:sqlite';
import { fileURLToPath } from 'node:url';
import { loadEnv, uid, nowIso, json, bodyJson, encrypt, decrypt, generateConceptVariants, synthesizeSpeech, generateVisual, renderVerticalVideo, testOpenAI, commandExists, tiktokExchangeCode, tiktokRefresh, tiktokCreatorInfo, tiktokInitVideo, tiktokUploadVideo, tiktokPostStatus, tiktokQueryVideos } from './lib.mjs';

const ROOT=path.dirname(fileURLToPath(import.meta.url));
loadEnv(path.join(ROOT,'.env'));
fs.mkdirSync(path.join(ROOT,'data'),{recursive:true});
fs.mkdirSync(path.join(ROOT,'storage','audio'),{recursive:true});
fs.mkdirSync(path.join(ROOT,'storage','videos'),{recursive:true});
fs.mkdirSync(path.join(ROOT,'storage','images'),{recursive:true});
const secretFile=path.join(ROOT,'data','.app-secret');
if(!process.env.APP_SECRET){if(!fs.existsSync(secretFile))fs.writeFileSync(secretFile,crypto.randomBytes(32).toString('hex'));process.env.APP_SECRET=fs.readFileSync(secretFile,'utf8').trim()}
const APP_SECRET=process.env.APP_SECRET, PORT=Number(process.env.PORT||3000);
const db=new DatabaseSync(path.join(ROOT,'data','autopilot.db'));
db.exec(`PRAGMA journal_mode=WAL;
CREATE TABLE IF NOT EXISTS settings (k TEXT PRIMARY KEY, v TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS secrets (k TEXT PRIMARY KEY, v TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS products (id TEXT PRIMARY KEY, name TEXT NOT NULL, category TEXT, price REAL DEFAULT 0, commission_rate REAL DEFAULT 0, affiliate_url TEXT, notes TEXT, active INTEGER DEFAULT 1, created_at TEXT);
CREATE TABLE IF NOT EXISTS contents (id TEXT PRIMARY KEY, product_id TEXT, status TEXT NOT NULL, niche TEXT, format TEXT, title TEXT, hook TEXT, script TEXT, caption TEXT, cta TEXT, visual_beats TEXT, video_path TEXT, audio_path TEXT, scheduled_at TEXT, privacy_level TEXT DEFAULT 'SELF_ONLY', publish_id TEXT, tiktok_status TEXT, post_id TEXT, views INTEGER DEFAULT 0, clicks INTEGER DEFAULT 0, orders INTEGER DEFAULT 0, revenue REAL DEFAULT 0, error TEXT, created_at TEXT, updated_at TEXT);
CREATE TABLE IF NOT EXISTS oauth (provider TEXT PRIMARY KEY, open_id TEXT, access_token TEXT, refresh_token TEXT, expires_at INTEGER, refresh_expires_at INTEGER, scopes TEXT, updated_at TEXT);
CREATE TABLE IF NOT EXISTS oauth_state (state TEXT PRIMARY KEY, created_at INTEGER);
CREATE TABLE IF NOT EXISTS experiments (id TEXT PRIMARY KEY, product_id TEXT, winner_content_id TEXT, variant_count INTEGER DEFAULT 0, created_at TEXT);
CREATE TABLE IF NOT EXISTS events (id TEXT PRIMARY KEY, type TEXT, message TEXT, created_at TEXT);
`);
function addColumn(t,d){try{db.exec(`ALTER TABLE ${t} ADD COLUMN ${d}`)}catch{}}
for(const d of ['score REAL DEFAULT 0','total_views INTEGER DEFAULT 0','total_clicks INTEGER DEFAULT 0','total_orders INTEGER DEFAULT 0','total_revenue REAL DEFAULT 0','updated_at TEXT','image_path TEXT'])addColumn('products',d);
for(const d of ['variant_group TEXT','variant_index INTEGER DEFAULT 0','hook_score REAL DEFAULT 0','approved_at TEXT','likes INTEGER DEFAULT 0','comments INTEGER DEFAULT 0','shares INTEGER DEFAULT 0','synced_at TEXT','image_path TEXT','optimized_at TEXT'])addColumn('contents',d);
const getSetting=(k,d='')=>db.prepare('SELECT v FROM settings WHERE k=?').get(k)?.v??d;
const setSetting=(k,v)=>db.prepare('INSERT INTO settings(k,v) VALUES(?,?) ON CONFLICT(k) DO UPDATE SET v=excluded.v').run(k,String(v));
const getSecret=k=>{const v=db.prepare('SELECT v FROM secrets WHERE k=?').get(k)?.v;return v?decrypt(v,APP_SECRET):''};
const setSecret=(k,v)=>{if(v===undefined||v===null||v==='')return;db.prepare('INSERT INTO secrets(k,v) VALUES(?,?) ON CONFLICT(k) DO UPDATE SET v=excluded.v').run(k,encrypt(String(v),APP_SECRET));process.env[k]=String(v)};
for(const k of ['OPENAI_API_KEY','TIKTOK_CLIENT_KEY','TIKTOK_CLIENT_SECRET','TIKTOK_REDIRECT_URI','TIKTOK_SCOPES']){const v=getSecret(k);if(v)process.env[k]=v}
const defaults={niche:'gadgets utiles',format:'probleme-solution',daily_count:'3',variants_per_product:'3',auto_render:'true',optimization_mode:'revenue',schedule_gap_minutes:'180',autopilot_enabled:'false',autopilot_hour:'10',min_views_to_optimize:'1000',auto_visuals:'true',demo_mode:process.env.DEMO_MODE||'true'};
for(const [k,v] of Object.entries(defaults))if(getSetting(k,'')==='')setSetting(k,v);
const isDemo=()=>getSetting('demo_mode','true')==='true';
function log(type,message){try{db.prepare('INSERT INTO events(id,type,message,created_at) VALUES(?,?,?,?)').run(uid(),type,String(message),nowIso())}catch{}}
function staticFile(res,pathname){const rel=pathname==='/'?'index.html':pathname.replace(/^\//,'');const file=path.join(ROOT,rel);if(!file.startsWith(ROOT)||!fs.existsSync(file)||fs.statSync(file).isDirectory())return false;const ext=path.extname(file),types={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webmanifest':'application/manifest+json'};const b=fs.readFileSync(file);res.writeHead(200,{'content-type':types[ext]||'application/octet-stream','content-length':b.length});res.end(b);return true}
function serveStorage(res,pathname){const rel=pathname.replace(/^\/storage\//,'');const file=path.join(ROOT,'storage',rel);if(!file.startsWith(path.join(ROOT,'storage'))||!fs.existsSync(file))return false;const ext=path.extname(file).toLowerCase(),types={'.mp4':'video/mp4','.jpg':'image/jpeg','.jpeg':'image/jpeg','.png':'image/png','.mp3':'audio/mpeg','.m4a':'audio/mp4'};const b=fs.readFileSync(file);res.writeHead(200,{'content-type':types[ext]||'application/octet-stream','content-length':b.length,'accept-ranges':'bytes'});res.end(b);return true}
const product=id=>id?db.prepare('SELECT * FROM products WHERE id=?').get(id):null;
function publicPath(p){if(!p)return null;return '/storage/'+path.relative(path.join(ROOT,'storage'),p).split(path.sep).join('/')}
function content(id){const c=db.prepare('SELECT * FROM contents WHERE id=?').get(id);if(!c)return null;try{c.visual_beats=JSON.parse(c.visual_beats||'[]')}catch{c.visual_beats=[]}c.video_url=publicPath(c.video_path);c.image_url=publicPath(c.image_path);c.product=product(c.product_id);return c}
function saveOauth(x){const now=Date.now();db.prepare(`INSERT INTO oauth(provider,open_id,access_token,refresh_token,expires_at,refresh_expires_at,scopes,updated_at) VALUES('tiktok',?,?,?,?,?,?,?) ON CONFLICT(provider) DO UPDATE SET open_id=excluded.open_id,access_token=excluded.access_token,refresh_token=excluded.refresh_token,expires_at=excluded.expires_at,refresh_expires_at=excluded.refresh_expires_at,scopes=excluded.scopes,updated_at=excluded.updated_at`).run(x.open_id||'',encrypt(x.access_token,APP_SECRET),encrypt(x.refresh_token,APP_SECRET),now+(x.expires_in||86400)*1000,now+(x.refresh_expires_in||31536000)*1000,x.scope||'',nowIso())}
function getOauth(){const x=db.prepare('SELECT * FROM oauth WHERE provider=?').get('tiktok');return x?{...x,access_token:decrypt(x.access_token,APP_SECRET),refresh_token:decrypt(x.refresh_token,APP_SECRET)}:null}
async function accessToken(){let o=getOauth();if(!o)throw new Error('TikTok non connecté');if(o.expires_at-Date.now()<300000){const n=await tiktokRefresh(o.refresh_token);saveOauth(n);o=getOauth()}return o.access_token}
function recalcProductScores(){for(const r of db.prepare(`SELECT p.id,p.price,p.commission_rate,COALESCE(SUM(c.views),0) views,COALESCE(SUM(c.clicks),0) clicks,COALESCE(SUM(c.orders),0) orders,COALESCE(SUM(c.revenue),0) revenue FROM products p LEFT JOIN contents c ON c.product_id=p.id GROUP BY p.id`).all()){const ctr=r.views?100*r.clicks/r.views:0,conv=r.clicks?100*r.orders/r.clicks:0,rpm=r.views?1000*r.revenue/r.views:0,commission=Number(r.price||0)*Number(r.commission_rate||0)/100,confidence=Math.min(1,Number(r.views||0)/10000);let score=getSetting('optimization_mode')==='conversion'?conv*5+ctr+commission*.1:rpm*.55+conv*2+ctr*.5+commission*.15;score*=.35+.65*confidence;db.prepare('UPDATE products SET score=?,total_views=?,total_clicks=?,total_orders=?,total_revenue=?,updated_at=? WHERE id=?').run(Number(score.toFixed(3)),r.views,r.clicks,r.orders,r.revenue,nowIso(),r.id)}}
function rankedProducts(limit=20){recalcProductScores();return db.prepare('SELECT * FROM products WHERE active=1 ORDER BY score DESC,commission_rate DESC,price DESC LIMIT ?').all(limit)}
function dashboard(){recalcProductScores();const t=db.prepare('SELECT COUNT(*) contents,COALESCE(SUM(views),0) views,COALESCE(SUM(clicks),0) clicks,COALESCE(SUM(orders),0) orders,COALESCE(SUM(revenue),0) revenue FROM contents').get(),ready=db.prepare("SELECT COUNT(*) n FROM contents WHERE status IN ('READY','SCHEDULED')").get().n,published=db.prepare("SELECT COUNT(*) n FROM contents WHERE status='PUBLISHED'").get().n;return {...t,ready,published,rpm:t.views?Number((1000*t.revenue/t.views).toFixed(2)):0,conversion:t.clicks?Number((100*t.orders/t.clicks).toFixed(2)):0}}
async function makeVariants(productId,count){const p=product(productId),group=uid(),niche=getSetting('niche'),format=getSetting('format'),concepts=await generateConceptVariants({product:p,niche,format,count}),out=[];for(let i=0;i<concepts.length;i++){const x=concepts[i],id=uid();db.prepare(`INSERT INTO contents(id,product_id,status,niche,format,title,hook,script,caption,cta,visual_beats,variant_group,variant_index,hook_score,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,p?.id||null,'SCRIPTED',niche,format,x.title,x.hook,x.script,x.caption,x.cta,JSON.stringify(x.visual_beats||[]),group,i,Number(x.hook_score||0),nowIso(),nowIso());out.push(content(id))}db.prepare('INSERT INTO experiments(id,product_id,variant_count,created_at) VALUES(?,?,?,?)').run(group,p?.id||null,out.length,nowIso());return out}
async function renderOne(id){const c=content(id);if(!c)throw new Error('Contenu introuvable');const p=product(c.product_id),audio=path.join(ROOT,'storage','audio',`${id}.${isDemo()?'m4a':'mp3'}`),video=path.join(ROOT,'storage','videos',`${id}.mp4`),image=path.join(ROOT,'storage','images',`${id}.jpg`);db.prepare('UPDATE contents SET status=?,error=NULL,updated_at=? WHERE id=?').run('RENDERING',nowIso(),id);try{process.env.DEMO_MODE=String(isDemo());await synthesizeSpeech(`${c.hook}. ${c.script} ${c.cta}`,audio);let imageFile=p?.image_path&&fs.existsSync(p.image_path)?p.image_path:null;if(!imageFile&&getSetting('auto_visuals')==='true'&&!isDemo()){try{imageFile=await generateVisual({product:p,concept:c,outFile:image})}catch(e){log('visual_error',e.message)}}await renderVerticalVideo({concept:c,audioFile:audio,outFile:video,product:p,imageFile});db.prepare('UPDATE contents SET status=?,audio_path=?,video_path=?,image_path=?,updated_at=? WHERE id=?').run('READY',audio,video,imageFile||null,nowIso(),id)}catch(e){db.prepare('UPDATE contents SET status=?,error=?,updated_at=? WHERE id=?').run('ERROR',String(e.message||e),nowIso(),id);throw e}return content(id)}
async function publishOne(id,privacyLevel){const c=content(id);if(!c?.video_path)throw new Error('Vidéo non rendue');if(!c.approved_at)throw new Error('Validation utilisateur requise avant publication');if(isDemo()){db.prepare('UPDATE contents SET status=?,tiktok_status=?,publish_id=?,privacy_level=?,post_id=?,updated_at=? WHERE id=?').run('PUBLISHED','DEMO_PUBLISHED','demo_'+uid(),privacyLevel||'SELF_ONLY','demo_post_'+uid(),nowIso(),id);return content(id)}const token=await accessToken(),info=await tiktokCreatorInfo(token),privacy=info.privacy_level_options?.includes(privacyLevel)?privacyLevel:'SELF_ONLY',size=fs.statSync(c.video_path).size,init=await tiktokInitVideo(token,{fileSize:size,title:c.caption,privacyLevel:privacy,disableComment:info.comment_disabled,disableDuet:info.duet_disabled,disableStitch:info.stitch_disabled});await tiktokUploadVideo(init.upload_url,c.video_path);db.prepare('UPDATE contents SET status=?,publish_id=?,privacy_level=?,tiktok_status=?,updated_at=? WHERE id=?').run('SUBMITTED',init.publish_id,privacy,'PROCESSING',nowIso(),id);return content(id)}
async function refreshStatuses(){if(isDemo())return;const rows=db.prepare("SELECT id,publish_id FROM contents WHERE publish_id IS NOT NULL AND status IN ('SUBMITTED','PROCESSING')").all();if(!rows.length)return;let token;try{token=await accessToken()}catch{return}for(const r of rows){try{const s=await tiktokPostStatus(token,r.publish_id),st=s.status||'PROCESSING',postId=s.publicaly_available_post_id?.[0]||s.publicly_available_post_id?.[0]||null;db.prepare('UPDATE contents SET tiktok_status=?,post_id=COALESCE(?,post_id),status=?,error=?,updated_at=? WHERE id=?').run(st,postId,st==='PUBLISH_COMPLETE'?'PUBLISHED':st==='FAILED'?'ERROR':'PROCESSING',s.fail_reason||null,nowIso(),r.id)}catch{}}}
async function syncMetrics(){if(isDemo())return {updated:0};const all=db.prepare("SELECT id,post_id FROM contents WHERE post_id IS NOT NULL AND status='PUBLISHED' AND post_id NOT LIKE 'demo_%'").all();if(!all.length)return{updated:0};const token=await accessToken();let updated=0;for(let i=0;i<all.length;i+=20){const rows=all.slice(i,i+20),data=await tiktokQueryVideos(token,rows.map(x=>x.post_id));for(const v of data.videos||[]){const r=rows.find(x=>String(x.post_id)===String(v.id));if(!r)continue;db.prepare('UPDATE contents SET views=?,likes=?,comments=?,shares=?,synced_at=?,updated_at=? WHERE id=?').run(v.view_count||0,v.like_count||0,v.comment_count||0,v.share_count||0,nowIso(),nowIso(),r.id);updated++}}recalcProductScores();return{updated}}
async function optimize(){const min=Number(getSetting('min_views_to_optimize','1000')),rows=db.prepare("SELECT * FROM contents WHERE status='PUBLISHED' AND optimized_at IS NULL AND views>=? ORDER BY revenue*1000.0/CASE WHEN views=0 THEN 1 ELSE views END DESC LIMIT 3").all(min);let created=0;for(const r of rows){const rpm=r.views?1000*r.revenue/r.views:0;if(rpm>0||r.orders>0){const v=await makeVariants(r.product_id,Math.min(3,Number(getSetting('variants_per_product'))));created+=v.length;db.prepare('UPDATE contents SET optimized_at=? WHERE id=?').run(nowIso(),r.id)}}return{created}}
async function runAutopilot(count){const target=Math.max(1,Math.min(12,Number(count||getSetting('daily_count')))),variants=Math.max(1,Math.min(5,Number(getSetting('variants_per_product')))),candidates=rankedProducts(target),out=[];if(!candidates.length)out.push(...await makeVariants(null,variants));else for(const p of candidates.slice(0,target))out.push(...await makeVariants(p.id,variants));if(getSetting('auto_render')==='true')for(const c of out)try{await renderOne(c.id)}catch(e){log('render_error',e.message)}return out}
async function schedulerTick(){try{await refreshStatuses();const now=new Date(),today=now.toISOString().slice(0,10);if(getSetting('autopilot_enabled')==='true'&&now.getHours()>=Number(getSetting('autopilot_hour','10'))&&getSetting('last_autopilot_date')!==today){await runAutopilot();setSetting('last_autopilot_date',today);log('autopilot','Génération quotidienne terminée')}const due=db.prepare("SELECT id,privacy_level FROM contents WHERE status IN ('READY','SCHEDULED') AND approved_at IS NOT NULL AND scheduled_at IS NOT NULL AND scheduled_at<=? LIMIT 1").all(now.toISOString());for(const r of due)try{await publishOne(r.id,r.privacy_level)}catch(e){db.prepare('UPDATE contents SET error=?,updated_at=? WHERE id=?').run(String(e.message||e),nowIso(),r.id)}await optimize()}catch(e){log('scheduler_error',e.message)}}
function decodeImage(data,id){if(!data)return null;const m=String(data).match(/^data:image\/(png|jpeg|jpg|webp);base64,(.+)$/);if(!m)throw new Error('Image invalide');const ext=m[1]==='jpeg'?'jpg':m[1],file=path.join(ROOT,'storage','images',`product-${id}.${ext}`);fs.writeFileSync(file,Buffer.from(m[2],'base64'));return file}
function parseCsv(text){const lines=String(text||'').split(/\r?\n/).filter(Boolean);if(!lines.length)return[];const sep=lines[0].includes(';')?';':',';const headers=lines[0].split(sep).map(x=>x.trim().toLowerCase());return lines.slice(1).map(line=>{const cells=line.split(sep).map(x=>x.trim());return Object.fromEntries(headers.map((h,i)=>[h,cells[i]??'']))})}
function setupStatus(){return{openai:!!process.env.OPENAI_API_KEY,tiktokApp:!!(process.env.TIKTOK_CLIENT_KEY&&process.env.TIKTOK_CLIENT_SECRET&&process.env.TIKTOK_REDIRECT_URI),ffmpeg:null,demo:isDemo(),redirectUri:process.env.TIKTOK_REDIRECT_URI||`http://localhost:${PORT}/oauth/tiktok/callback`,scopes:process.env.TIKTOK_SCOPES||'user.info.basic,video.publish,video.list'}}

const server=http.createServer(async(req,res)=>{const url=new URL(req.url,`http://${req.headers.host}`),p=url.pathname;try{
if(p.startsWith('/storage/')){if(serveStorage(res,p))return}
if(p==='/api/state'&&req.method==='GET'){const o=db.prepare('SELECT open_id,scopes,expires_at,updated_at FROM oauth WHERE provider=?').get('tiktok');return json(res,200,{settings:Object.fromEntries(Object.keys(defaults).map(k=>[k,['daily_count','variants_per_product','schedule_gap_minutes','autopilot_hour','min_views_to_optimize'].includes(k)?Number(getSetting(k)):['auto_render','autopilot_enabled','auto_visuals'].includes(k)?getSetting(k)==='true':getSetting(k)])),products:rankedProducts(100).map(x=>({...x,image_url:publicPath(x.image_path)})),contents:db.prepare('SELECT id FROM contents ORDER BY created_at DESC LIMIT 200').all().map(x=>content(x.id)),dashboard:dashboard(),tiktok:o?{connected:true,...o}:{connected:false},setup:setupStatus(),events:db.prepare('SELECT * FROM events ORDER BY created_at DESC LIMIT 12').all()})}
if(p==='/api/settings'&&req.method==='POST'){const b=await bodyJson(req);for(const k of Object.keys(defaults))if(k in b)setSetting(k,b[k]);return json(res,200,{ok:true})}
if(p==='/api/setup'&&req.method==='POST'){const b=await bodyJson(req);for(const k of ['OPENAI_API_KEY','TIKTOK_CLIENT_KEY','TIKTOK_CLIENT_SECRET','TIKTOK_REDIRECT_URI','TIKTOK_SCOPES'])if(b[k])setSecret(k,b[k]);if('demo_mode'in b)setSetting('demo_mode',!!b.demo_mode);return json(res,200,{ok:true,status:setupStatus()})}
if(p==='/api/setup/test'&&req.method==='POST'){const ffmpeg=await commandExists('ffmpeg');let openai=false,openaiError='';if(process.env.OPENAI_API_KEY)try{openai=await testOpenAI()}catch(e){openaiError=e.message}return json(res,200,{ffmpeg,openai,openaiError,tiktokApp:!!(process.env.TIKTOK_CLIENT_KEY&&process.env.TIKTOK_CLIENT_SECRET&&process.env.TIKTOK_REDIRECT_URI)})}
if(p==='/api/products'&&req.method==='POST'){const b=await bodyJson(req),id=uid(),img=decodeImage(b.image_data,id);db.prepare('INSERT INTO products(id,name,category,price,commission_rate,affiliate_url,notes,image_path,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)').run(id,b.name,b.category||'',Number(b.price||0),Number(b.commission_rate||0),b.affiliate_url||'',b.notes||'',img,nowIso(),nowIso());return json(res,201,{product:product(id)})}
if(p==='/api/products/import'&&req.method==='POST'){const b=await bodyJson(req),rows=parseCsv(b.csv);let n=0;for(const r of rows){const name=r.name||r.nom||r.produit;if(!name)continue;db.prepare('INSERT INTO products(id,name,category,price,commission_rate,affiliate_url,notes,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)').run(uid(),name,r.category||r.categorie||'',Number(r.price||r.prix||0),Number(r.commission_rate||r.commission||0),r.affiliate_url||r.lien||'',r.notes||r.description||'',nowIso(),nowIso());n++}return json(res,200,{imported:n})}
if(p.startsWith('/api/products/')&&req.method==='DELETE'){db.prepare('DELETE FROM products WHERE id=?').run(p.split('/').pop());return json(res,200,{ok:true})}
if(p==='/api/autopilot/run'&&req.method==='POST'){const b=await bodyJson(req);return json(res,201,{contents:await runAutopilot(b.count)})}
if(/^\/api\/contents\/[^/]+\/render$/.test(p)&&req.method==='POST')return json(res,200,{content:await renderOne(p.split('/')[3])});
if(/^\/api\/contents\/[^/]+\/approve$/.test(p)&&req.method==='POST'){const id=p.split('/')[3],b=await bodyJson(req),c=content(id);if(!c?.video_path)throw new Error('Rends la vidéo avant approbation');db.prepare('UPDATE contents SET approved_at=?,scheduled_at=?,privacy_level=?,status=?,updated_at=? WHERE id=?').run(nowIso(),b.scheduled_at||nowIso(),b.privacy_level||'SELF_ONLY','SCHEDULED',nowIso(),id);return json(res,200,{content:content(id)})}
if(/^\/api\/contents\/[^/]+\/publish$/.test(p)&&req.method==='POST'){const id=p.split('/')[3],b=await bodyJson(req);if(!content(id)?.approved_at)db.prepare('UPDATE contents SET approved_at=?,privacy_level=?,updated_at=? WHERE id=?').run(nowIso(),b.privacy_level||'SELF_ONLY',nowIso(),id);return json(res,200,{content:await publishOne(id,b.privacy_level)})}
if(/^\/api\/contents\/[^/]+\/metrics$/.test(p)&&req.method==='POST'){const id=p.split('/')[3],b=await bodyJson(req);db.prepare('UPDATE contents SET views=?,clicks=?,orders=?,revenue=?,updated_at=? WHERE id=?').run(Number(b.views||0),Number(b.clicks||0),Number(b.orders||0),Number(b.revenue||0),nowIso(),id);recalcProductScores();return json(res,200,{content:content(id)})}
if(/^\/api\/contents\/[^/]+\/clone-winner$/.test(p)&&req.method==='POST'){const c=content(p.split('/')[3]);if(!c)throw new Error('Contenu introuvable');return json(res,201,{contents:await makeVariants(c.product_id,Number(getSetting('variants_per_product')))})}
if(p==='/api/tiktok/creator-info'&&req.method==='GET'){if(isDemo())return json(res,200,{creator_username:'demo',privacy_level_options:['SELF_ONLY','PUBLIC_TO_EVERYONE'],comment_disabled:false,duet_disabled:false,stitch_disabled:false,max_video_post_duration_sec:300});return json(res,200,await tiktokCreatorInfo(await accessToken()))}
if(p==='/api/sync-metrics'&&req.method==='POST')return json(res,200,await syncMetrics());
if(p==='/api/refresh-status'&&req.method==='POST'){await refreshStatuses();return json(res,200,{ok:true})}
if(p==='/api/optimize'&&req.method==='POST')return json(res,200,await optimize());
if(p==='/oauth/tiktok/start'&&req.method==='GET'){if(!process.env.TIKTOK_CLIENT_KEY||!process.env.TIKTOK_REDIRECT_URI)return json(res,400,{error:'Configure les identifiants TikTok dans Configuration'});const state=crypto.randomBytes(24).toString('base64url');db.prepare('INSERT INTO oauth_state(state,created_at) VALUES(?,?)').run(state,Date.now());const q=new URLSearchParams({client_key:process.env.TIKTOK_CLIENT_KEY,response_type:'code',scope:process.env.TIKTOK_SCOPES||'user.info.basic,video.publish,video.list',redirect_uri:process.env.TIKTOK_REDIRECT_URI,state});res.writeHead(302,{location:'https://www.tiktok.com/v2/auth/authorize/?'+q});return res.end()}
if(p==='/oauth/tiktok/callback'&&req.method==='GET'){const code=url.searchParams.get('code'),state=url.searchParams.get('state'),row=state&&db.prepare('SELECT * FROM oauth_state WHERE state=?').get(state);if(!code||!row||Date.now()-row.created_at>600000)return json(res,400,{error:'OAuth TikTok invalide ou expiré'});db.prepare('DELETE FROM oauth_state WHERE state=?').run(state);saveOauth(await tiktokExchangeCode(code));res.writeHead(302,{location:'/'});return res.end()}
if(p==='/api/tiktok/disconnect'&&req.method==='POST'){db.prepare('DELETE FROM oauth WHERE provider=?').run('tiktok');return json(res,200,{ok:true})}
if(staticFile(res,p))return;return json(res,404,{error:'Introuvable'});
}catch(e){console.error(e);log('error',e.message||e);return json(res,500,{error:String(e.message||e)})}});
setInterval(schedulerTick,60000);setTimeout(schedulerTick,1500);
server.listen(PORT,()=>console.log(`TikTok Autopilot COMPLETE → http://localhost:${PORT}`));
